---
- name: install haproxy and keepalived on Debin
  when: target_os_family == 'Debian'
  apt: name={{item}} state=latest update_cache=true
  with_items:
      - haproxy
      - keepalived

- name: install haproxy and keepalived on CentOS
  when: target_os_family == 'RedHat'
  yum: name={{item}} state=latest update_cache=true
  with_items:
      - haproxy
      - keepalived


- name: start haproxy and keepalived
  service: name={{item}} state=started enabled=yes
  with_items:
      - haproxy
      - keepalived

      
