---
- name: install haproxy and keepalived on Debin
  when: target_os_family == 'Debian'
  apt: 
    name: ['haproxy', 'keepalived'] 
    state: latest 
    update_cache: true

- name: install haproxy and keepalived on CentOS
  when: target_os_family == 'RedHat'
  yum: 
    name: ['haproxy', 'keepalived'] 
    state: latest 
    update_cache: true

- name: custom haproxy configuration 
  template: 
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
#  notify: restart chronyd

#- name: start haproxy and keepalived
#  service: name={{item}} state=started enabled=yes
#  with_items:
#      - haproxy
#      - keepalived