---
- name: install chrony on Debin
  when: target_os_family == 'Debian'
  apt: name={{item}} state=latest update_cache=true
  with_items:
      - chrony

- name: install chrony on CentOS
  when: target_os_family == 'RedHat'
  yum: name={{item}} state=latest update_cache=true
  with_items:
      - chrony

- name: Copy chronyd configuration 
  template: src=chrony.conf dest=/etc/chrony.conf
  notify: restart chronyd

- name: chronyd state
  service: name=chronyd state=started enabled=yes

- name: change timezone
  file:
    src: /usr/share/zoneinfo/Asia/Shanghai
    dest: /etc/localtime
    state: link

- name: run hwclock
  command: hwclock --systohc
